{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"mount_file_id":"1sdRlRZQoPT0gs5NmnTUgyN4k5JCftgJe","authorship_tag":"ABX9TyO4p9T3LdYT7+LSqmxtb0bJ"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["from google.colab import drive\n","drive.mount('/content/drive/')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"iMZR7VZ0kUE5","executionInfo":{"status":"ok","timestamp":1708237573823,"user_tz":-120,"elapsed":3129,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"ea29fd78-2acb-404d-c408-88bc836710bf"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount(\"/content/drive/\", force_remount=True).\n"]}]},{"cell_type":"code","source":["%cd '/content/drive/MyDrive/nlp-with-deep-learning/03 - neural-machine-translator'"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"P_FSD5Ext98X","executionInfo":{"status":"ok","timestamp":1708237820015,"user_tz":-120,"elapsed":403,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"5bd88552-cd1b-417f-d790-5eae5cd60614"},"execution_count":16,"outputs":[{"output_type":"stream","name":"stdout","text":["/content/drive/MyDrive/nlp-with-deep-learning/03 - neural-machine-translator\n"]}]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"Q76v8WlzjHJm","executionInfo":{"status":"ok","timestamp":1708237575203,"user_tz":-120,"elapsed":1384,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"d4849f63-2bb8-402b-ac5e-cc7c29d38da3"},"outputs":[{"output_type":"stream","name":"stdout","text":["\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0m✨🍰✨ Everything looks OK!\n"]}],"source":["!pip install -q condacolab\n","import condacolab\n","condacolab.install()"]},{"cell_type":"code","source":["!conda --version"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"DJJNHANdq-Jy","executionInfo":{"status":"ok","timestamp":1708237576236,"user_tz":-120,"elapsed":1036,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"81dd85c4-85b2-4771-8dd3-d671da266c0e"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["conda 23.11.0\n"]}]},{"cell_type":"code","source":["!conda init -q bash"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3UY2XnkzrU-c","executionInfo":{"status":"ok","timestamp":1708237577334,"user_tz":-120,"elapsed":1103,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"4d903c18-f16e-4d11-80b7-fae0912adfaa"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["no change     /usr/local/condabin/conda\n","no change     /usr/local/bin/conda\n","no change     /usr/local/bin/conda-env\n","no change     /usr/local/bin/activate\n","no change     /usr/local/bin/deactivate\n","no change     /usr/local/etc/profile.d/conda.sh\n","no change     /usr/local/etc/fish/conf.d/conda.fish\n","no change     /usr/local/shell/condabin/Conda.psm1\n","no change     /usr/local/shell/condabin/conda-hook.ps1\n","no change     /usr/local/lib/python3.10/site-packages/xontrib/conda.xsh\n","no change     /usr/local/etc/profile.d/conda.csh\n","modified      /root/.bashrc\n","\n","==> For changes to take effect, close and re-open your current shell. <==\n","\n"]}]},{"cell_type":"code","source":["!conda env create -f local_env.yml"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"neHfJLIOwrr_","executionInfo":{"status":"ok","timestamp":1708237578875,"user_tz":-120,"elapsed":1546,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"7fb01f06-c5c3-4bff-f2e4-1e67af36905c"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","CondaValueError: prefix already exists: /usr/local/envs/local_nmt\n","\n"]}]},{"cell_type":"code","source":["!conda activate local_nmt"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"okIqWZE6rMF_","executionInfo":{"status":"ok","timestamp":1708237731059,"user_tz":-120,"elapsed":37,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"22c3b956-2967-429a-f92e-be255bf45780"},"execution_count":13,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","CondaError: Run 'conda init' before 'conda activate'\n","\n"]}]},{"cell_type":"code","source":["!pip install ipykernel"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"knq0T6CM4FN_","executionInfo":{"status":"ok","timestamp":1708237580621,"user_tz":-120,"elapsed":1069,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"74b05f2c-79c3-4845-fb5a-00b4a31cea4b"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: ipykernel in /usr/local/lib/python3.10/site-packages (6.29.2)\n","Requirement already satisfied: comm>=0.1.1 in /usr/local/lib/python3.10/site-packages (from ipykernel) (0.2.1)\n","Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.10/site-packages (from ipykernel) (1.8.1)\n","Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.10/site-packages (from ipykernel) (8.21.0)\n","Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.10/site-packages (from ipykernel) (8.6.0)\n","Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.10/site-packages (from ipykernel) (5.7.1)\n","Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.10/site-packages (from ipykernel) (0.1.6)\n","Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/site-packages (from ipykernel) (1.6.0)\n","Requirement already satisfied: packaging in /usr/local/lib/python3.10/site-packages (from ipykernel) (23.2)\n","Requirement already satisfied: psutil in /usr/local/lib/python3.10/site-packages (from ipykernel) (5.9.8)\n","Requirement already satisfied: pyzmq>=24 in /usr/local/lib/python3.10/site-packages (from ipykernel) (25.1.2)\n","Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.10/site-packages (from ipykernel) (6.4)\n","Requirement already satisfied: traitlets>=5.4.0 in /usr/local/lib/python3.10/site-packages (from ipykernel) (5.14.1)\n","Requirement already satisfied: decorator in /usr/local/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)\n","Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (0.19.1)\n","Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (3.0.43)\n","Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (2.17.2)\n","Requirement already satisfied: stack-data in /usr/local/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)\n","Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (1.2.0)\n","Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)\n","Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/site-packages (from jupyter-client>=6.1.12->ipykernel) (2.8.2)\n","Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.1.0)\n","Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.3)\n","Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel) (0.7.0)\n","Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.13)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.16.0)\n","Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (2.0.1)\n","Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (2.4.1)\n","Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.2.2)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0m"]}]},{"cell_type":"code","source":["!python -m ipykernel install --user --name local_nmt"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"7OjSgB43wdAz","executionInfo":{"status":"ok","timestamp":1708237581229,"user_tz":-120,"elapsed":614,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"9f72e35b-541f-41df-d61a-5c1b30a8c514"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Installed kernelspec local_nmt in /root/.local/share/jupyter/kernels/local_nmt\n"]}]},{"cell_type":"code","source":["!mamba env list"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"lKNXlLUV4cp7","executionInfo":{"status":"ok","timestamp":1708237744236,"user_tz":-120,"elapsed":1082,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"843bb84a-0ac1-44ac-da94-3b5b3c8d564c"},"execution_count":14,"outputs":[{"output_type":"stream","name":"stdout","text":["# conda environments:\n","#\n","base                     /usr/local\n","local_nmt                /usr/local/envs/local_nmt\n","\n"]}]},{"cell_type":"code","source":["!mamba init"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"RaEPyjMS4_a-","executionInfo":{"status":"ok","timestamp":1708237582482,"user_tz":-120,"elapsed":602,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"9b1f90b1-cf21-402b-f257-fdb707984860"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["no change     /usr/local/condabin/conda\n","no change     /usr/local/bin/conda\n","no change     /usr/local/bin/conda-env\n","no change     /usr/local/bin/activate\n","no change     /usr/local/bin/deactivate\n","no change     /usr/local/etc/profile.d/conda.sh\n","no change     /usr/local/etc/fish/conf.d/conda.fish\n","no change     /usr/local/shell/condabin/Conda.psm1\n","no change     /usr/local/shell/condabin/conda-hook.ps1\n","no change     /usr/local/lib/python3.10/site-packages/xontrib/conda.xsh\n","no change     /usr/local/etc/profile.d/conda.csh\n","no change     /root/.bashrc\n","No action taken.\n","Added mamba to /root/.bashrc\n","\n","==> For changes to take effect, close and re-open your current shell. <==\n","\n"]}]},{"cell_type":"code","source":["!mamba activate local_nmt"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"w7Jqpm7846Z-","executionInfo":{"status":"ok","timestamp":1708237767948,"user_tz":-120,"elapsed":1028,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"4a242a52-a501-4322-fa7d-50b7642e09e8"},"execution_count":15,"outputs":[{"output_type":"stream","name":"stdout","text":["Run 'mamba init' to be able to run mamba activate/deactivate\n","and start a new shell session. Or use conda to activate/deactivate.\n","\n"]}]},{"cell_type":"code","source":["!python run.py"],"metadata":{"id":"hy0vehUN6L6P","executionInfo":{"status":"ok","timestamp":1708237852002,"user_tz":-120,"elapsed":375,"user":{"displayName":"Thibatsane Mahlelebe","userId":"14879776208084310062"}},"outputId":"8e712954-e921-4bae-f8c5-1a3364b074b3","colab":{"base_uri":"https://localhost:8080/"}},"execution_count":17,"outputs":[{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/content/drive/MyDrive/nlp-with-deep-learning/03 - neural-machine-translator/run.py\", line 51, in <module>\n","    from docopt import docopt\n","ModuleNotFoundError: No module named 'docopt'\n"]}]}]}